[project]
name = "bgg-exploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.21.0",
    "pydantic>=2.10.5",
    "requests>=2.32.3",
]
